-- MySQL Script generated by MySQL Workbench
-- Mon Jun 15 22:38:55 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema besttrip_chamsi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema besttrip_chamsi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `besttrip_chamsi_chamsi` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `besttrip_chamsi_chamsi` ;

-- -----------------------------------------------------
-- Table `besttrip_chamsi`.`Compte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `besttrip_chamsi`.`Compte` ;

CREATE TABLE IF NOT EXISTS `besttrip_chamsi`.`Compte` (
  `id_compte` INT(20) NOT NULL AUTO_INCREMENT,
  `nom_compte` VARCHAR(45) NULL,
  `prenom_compte` VARCHAR(45) NULL,
  `dob_compte` DATE NULL,
  `country_compte` INT(3) NULL,
  `login_compte` VARCHAR(20) NULL,
  `pwd_compte` VARCHAR(20) NULL,
  `type_compte` VARCHAR(20) NULL,
  `status_compte` INT(1) NULL,
  PRIMARY KEY (`id_compte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `besttrip_chamsi`.`Recommander`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `besttrip_chamsi`.`Recommander` ;

CREATE TABLE IF NOT EXISTS `besttrip_chamsi`.`Recommander` (
  `id_recommander` INT NOT NULL AUTO_INCREMENT,
  `type_recommander` VARCHAR(20) NULL,
  `Compte_id_compte` INT(20) NOT NULL,
  PRIMARY KEY (`id_recommander`, `Compte_id_compte`),
  INDEX `fk_Recommander_Compte_idx` (`Compte_id_compte` ASC),
  CONSTRAINT `fk_Recommander_Compte`
    FOREIGN KEY (`Compte_id_compte`)
    REFERENCES `besttrip_chamsi`.`Compte` (`id_compte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `besttrip_chamsi`.`Text`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `besttrip_chamsi`.`Text` ;

CREATE TABLE IF NOT EXISTS `besttrip_chamsi`.`Text` (
  `id_text` INT NOT NULL AUTO_INCREMENT,
  `description_experience` VARCHAR(45) NULL,
  PRIMARY KEY (`id_text`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `besttrip_chamsi`.`Video`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `besttrip_chamsi`.`Video` ;

CREATE TABLE IF NOT EXISTS `besttrip_chamsi`.`Video` (
  `id_video` INT NOT NULL AUTO_INCREMENT,
  `title_video` VARCHAR(45) NULL,
  `path_video` VARCHAR(45) NULL,
  PRIMARY KEY (`id_video`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `besttrip_chamsi`.`Image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `besttrip_chamsi`.`Image` ;

CREATE TABLE IF NOT EXISTS `besttrip_chamsi`.`Image` (
  `id_image` INT NOT NULL AUTO_INCREMENT,
  `path_url_image` VARCHAR(45) NULL,
  PRIMARY KEY (`id_image`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `besttrip_chamsi`.`Experience`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `besttrip_chamsi`.`Experience` ;

CREATE TABLE IF NOT EXISTS `besttrip_chamsi`.`Experience` (
  `id_experience` INT NOT NULL AUTO_INCREMENT,
  `title_experience` VARCHAR(45) NULL,
  `decalage_horaire_experience` INT(10) NULL,
  `start_experience` DATE NULL,
  `end_experience` DATE NULL,
  `season_experience` INT(2) NULL,
  `depense_experience` FLOAT(5) NULL,
  `note_experience` INT(10) NULL,
  `id_text` INT NOT NULL,
  `id_video` INT NOT NULL,
  `id_image` INT NOT NULL,
  `id_compte` INT(20) NOT NULL,
  PRIMARY KEY (`id_experience`, `id_text`, `id_video`, `id_image`, `id_compte`),
  INDEX `fk_Experience_Text1_idx` (`id_text` ASC),
  INDEX `fk_Experience_Video1_idx` (`id_video` ASC),
  INDEX `fk_Experience_Image1_idx` (`id_image` ASC),
  INDEX `fk_Experience_Compte1_idx` (`id_compte` ASC),
  CONSTRAINT `fk_Experience_Text1`
    FOREIGN KEY (`id_text`)
    REFERENCES `besttrip_chamsi`.`Text` (`id_text`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Experience_Video1`
    FOREIGN KEY (`id_video`)
    REFERENCES `besttrip_chamsi`.`Video` (`id_video`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Experience_Image1`
    FOREIGN KEY (`id_image`)
    REFERENCES `besttrip_chamsi`.`Image` (`id_image`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Experience_Compte1`
    FOREIGN KEY (`id_compte`)
    REFERENCES `besttrip_chamsi`.`Compte` (`id_compte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `besttrip_chamsi`.`Country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `besttrip_chamsi`.`Country` ;

CREATE TABLE IF NOT EXISTS `besttrip_chamsi`.`Country` (
  `id_country` INT NOT NULL AUTO_INCREMENT,
  `name_country` VARCHAR(45) NULL,
  PRIMARY KEY (`id_country`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `besttrip_chamsi`.`Guide`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `besttrip_chamsi`.`Guide` ;

CREATE TABLE IF NOT EXISTS `besttrip_chamsi`.`Guide` (
  `id_guide` INT NOT NULL AUTO_INCREMENT,
  `name_guide` VARCHAR(45) NULL,
  `description_guide` VARCHAR(45) NULL,
  `note_guide` VARCHAR(45) NULL,
  `statuts_guide` INT(2) NULL,
  `id_country` INT NOT NULL,
  `id_compte` INT(20) NOT NULL,
  PRIMARY KEY (`id_guide`, `id_country`, `id_compte`),
  INDEX `fk_Guide_Country1_idx` (`id_country` ASC),
  INDEX `fk_Guide_Compte1_idx` (`id_compte` ASC),
  CONSTRAINT `fk_Guide_Country`
    FOREIGN KEY (`id_country`)
    REFERENCES `besttrip_chamsi`.`Country` (`id_country`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Guide_Compte`
    FOREIGN KEY (`id_compte`)
    REFERENCES `besttrip_chamsi`.`Compte` (`id_compte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `besttrip_chamsi`.`ville`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `besttrip_chamsi`.`ville` ;

CREATE TABLE IF NOT EXISTS `besttrip_chamsi`.`ville` (
  `id_ville` INT NOT NULL AUTO_INCREMENT,
  `nom_ville` VARCHAR(45) NULL,
  `score_ville` VARCHAR(45) NULL,
  PRIMARY KEY (`id_ville`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `besttrip_chamsi`.`Lieu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `besttrip_chamsi`.`Lieu` ;

CREATE TABLE IF NOT EXISTS `besttrip_chamsi`.`Lieu` (
  `id_lieu` INT NOT NULL AUTO_INCREMENT,
  `nom_lieu` VARCHAR(45) NULL,
  `score_lieu` INT NULL,
  PRIMARY KEY (`id_lieu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `besttrip_chamsi`.`Companie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `besttrip_chamsi`.`Companie` ;

CREATE TABLE IF NOT EXISTS `besttrip_chamsi`.`Companie` (
  `id_companie` INT NOT NULL AUTO_INCREMENT,
  `nom_companie` VARCHAR(45) NULL,
  `score_companie` INT NULL,
  PRIMARY KEY (`id_companie`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
