/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import daoLayer.ExperienceDao;
import javax.swing.JOptionPane;

/**
 *
 * @author mac
 */
public class ConsulterExperience extends javax.swing.JFrame {
    
    /**
     * Creates new form TableauDeBord
     */
    public ConsulterExperience() {
        initComponents();

        this.title_experience.setText(GestionExperience.titleExperience);
        this.title_experience.disable();
        this.decalage_horaire.setText(Integer.toString(GestionExperience.decalage_horaire_experience));
        this.decalage_horaire.disable();

        this.start_experience.setText(GestionExperience.start_experience);
        this.start_experience.disable();
        
        this.end_experience.setText(GestionExperience.end_experience);
        this.end_experience.disable();
        
        //this.season_experience.setText(GestionExperience.season_experience);
        this.season_experience.setText("sdsqdsq");
        this.season_experience.disable();
        
        this.depense_experience.setText(Float.toString(GestionExperience.depense_experience));
        this.depense_experience.disable();
        
        this.note_experience.setText(Integer.toString(GestionExperience.note_experience));
        this.note_experience.disable();
        
        this.texte_exp.setText(GestionExperience.text_experience);
        this.texte_exp.disable();
        
        this.video_experience.setText(GestionExperience.video_experience);
        this.video_experience.disable();

        this.image_exp.setText(GestionExperience.image_experience);
        this.image_exp.disable();
        
        this.compte_experience.setText(GestionExperience.compte_experience);
        this.compte_experience.disable();
        
        this.country_exp.setText(GestionExperience.country_experience);
        this.country_exp.disable();
        this.compte_experience.disable();
        String status;
        if(GestionExperience.status_experience == 1)
             status = "Activé";
        else
             status = "Désactivé";
        
        this.statusExperience.setText(status);
        this.statusExperience.disable();
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        image_exp = new javax.swing.JTextField();
        returnExperience = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        texte_exp = new javax.swing.JTextArea();
        title_experience = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        depense_experience = new javax.swing.JTextField();
        statusExperience = new javax.swing.JTextField();
        btnDisableUser = new javax.swing.JButton();
        video_experience = new javax.swing.JTextField();
        end_experience = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pays = new javax.swing.JLabel();
        deleteExperience = new javax.swing.JToggleButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnEnableUser = new javax.swing.JButton();
        compte_experience = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        country_exp = new javax.swing.JTextField();
        jNom = new javax.swing.JLabel();
        start_experience = new javax.swing.JTextField();
        season_experience = new javax.swing.JTextField();
        decalage_horaire = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sur_dix = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        note_experience = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        userManage = new javax.swing.JMenu();
        guideManage = new javax.swing.JMenu();
        experienceManage = new javax.swing.JMenu();
        statManage = new javax.swing.JMenu();
        rssManage = new javax.swing.JMenu();
        newsletterManage = new javax.swing.JMenu();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(image_exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 180, 30));

        returnExperience.setText("<< précédent");
        returnExperience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnExperienceActionPerformed(evt);
            }
        });
        getContentPane().add(returnExperience, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, -1, -1));

        texte_exp.setColumns(20);
        texte_exp.setRows(5);
        jScrollPane1.setViewportView(texte_exp);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 180, -1));

        title_experience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                title_experienceActionPerformed(evt);
            }
        });
        getContentPane().add(title_experience, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 180, 30));

        jLabel10.setText("Vidéo :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        jLabel2.setText("Décalage horaire :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 100, -1));
        getContentPane().add(depense_experience, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 180, 30));
        getContentPane().add(statusExperience, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 180, 30));

        btnDisableUser.setText("Désactivé");
        btnDisableUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisableUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnDisableUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, -1, -1));
        getContentPane().add(video_experience, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 180, 30));
        getContentPane().add(end_experience, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 180, 30));

        jLabel4.setText("Date de fin :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 70, -1));

        pays.setText("Pays : ");
        getContentPane().add(pays, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 40, 20));

        deleteExperience.setText("Supprimer");
        deleteExperience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteExperienceActionPerformed(evt);
            }
        });
        getContentPane().add(deleteExperience, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 105, -1));

        jLabel11.setText("Image :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        jLabel7.setText("Note : ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        btnEnableUser.setText("Activé");
        btnEnableUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnableUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnableUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 80, -1));
        getContentPane().add(compte_experience, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 180, 30));

        jLabel5.setText("Saison : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 60, 20));
        getContentPane().add(country_exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 180, 30));

        jNom.setText("Titre : ");
        getContentPane().add(jNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 40, 20));
        getContentPane().add(start_experience, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 180, 30));
        getContentPane().add(season_experience, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 180, 30));
        getContentPane().add(decalage_horaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 180, 30));

        jLabel6.setText("Dépense :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 60, -1));

        sur_dix.setText("/10");
        getContentPane().add(sur_dix, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 34, 20));

        jLabel3.setText("Date de début :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 90, -1));
        getContentPane().add(note_experience, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 150, 30));

        jLabel9.setText("Description : ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 70, -1));

        jLabel12.setText("Propriétaire :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 70, 20));

        jLabel13.setText("Status :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/http-www.bhutantravelshop.com-wp-content-uploads-2014-07-lt.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 540));

        userManage.setText("Utilisateurs");
        userManage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userManageMouseClicked(evt);
            }
        });
        jMenuBar1.add(userManage);

        guideManage.setText("Guides");
        guideManage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guideManageMouseClicked(evt);
            }
        });
        jMenuBar1.add(guideManage);

        experienceManage.setText("Experiences");
        experienceManage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                experienceManageMouseClicked(evt);
            }
        });
        jMenuBar1.add(experienceManage);

        statManage.setText("Statistiques");
        statManage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statManageMouseClicked(evt);
            }
        });
        jMenuBar1.add(statManage);

        rssManage.setText("Flux Rss");
        rssManage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rssManageMouseClicked(evt);
            }
        });
        jMenuBar1.add(rssManage);

        newsletterManage.setText("Newsletter");
        newsletterManage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newsletterManageMouseClicked(evt);
            }
        });
        jMenuBar1.add(newsletterManage);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userManageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userManageMouseClicked
        // TODO add your handling code here:
            GestionUtilisateur userManage = new GestionUtilisateur();
            userManage.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_userManageMouseClicked

    private void btnEnableUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnableUserActionPerformed
        // TODO add your handling code here:
            ExperienceDao cDao = ExperienceDao.getInstance();
            cDao.disableExperience(GestionExperience.idExperience, true);
            GestionExperience.status_experience = 1;
            
    }//GEN-LAST:event_btnEnableUserActionPerformed

    private void btnDisableUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisableUserActionPerformed
        // TODO add your handling code here:
            ExperienceDao cDao = ExperienceDao.getInstance();
            cDao.disableExperience(GestionExperience.idExperience, false);
            GestionExperience.status_experience = 0;

    }//GEN-LAST:event_btnDisableUserActionPerformed

    private void returnExperienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnExperienceActionPerformed
        // TODO add your handling code here:
            this.returnExperienceForm();
    }//GEN-LAST:event_returnExperienceActionPerformed

    private void title_experienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_title_experienceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_title_experienceActionPerformed

    private void deleteExperienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteExperienceActionPerformed
        // TODO add your handling code here:
            ExperienceDao experienceDao               = ExperienceDao.getInstance();

            JOptionPane jop = new JOptionPane();

            if(experienceDao.deleteEntity(GestionExperience.expStatic)){
                jop.showMessageDialog(null, "Suppression de "+GestionExperience.titleExperience+" avec sucess", "Sucess", JOptionPane.ERROR_MESSAGE);
            }
            this.returnExperienceForm();

    }//GEN-LAST:event_deleteExperienceActionPerformed

    private void guideManageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guideManageMouseClicked
        // TODO add your handling code here:
            GestionGuide guideManage = new GestionGuide();
            guideManage.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_guideManageMouseClicked

    private void experienceManageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_experienceManageMouseClicked
        // TODO add your handling code here:
            GestionExperience experienceManage = new GestionExperience();
            experienceManage.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_experienceManageMouseClicked

    private void statManageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statManageMouseClicked
        // TODO add your handling code here:
            GestionStat statManage = new GestionStat();
            statManage.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_statManageMouseClicked

    private void rssManageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rssManageMouseClicked
        // TODO add your handling code here:
            GestionFlux rssManage = new GestionFlux();
            rssManage.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_rssManageMouseClicked

    private void newsletterManageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newsletterManageMouseClicked
        // TODO add your handling code here:
            GestionNewsletter newsletterManage = new GestionNewsletter();
            newsletterManage.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_newsletterManageMouseClicked
    
    public void returnExperienceForm(){
        GestionExperience expForm = new GestionExperience();
        expForm.setVisible(true);
        this.setVisible(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsulterExperience.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsulterExperience.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsulterExperience.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsulterExperience.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsulterExperience().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDisableUser;
    private javax.swing.JButton btnEnableUser;
    private javax.swing.JTextField compte_experience;
    private javax.swing.JTextField country_exp;
    private javax.swing.JTextField decalage_horaire;
    private javax.swing.JToggleButton deleteExperience;
    private javax.swing.JTextField depense_experience;
    private javax.swing.JTextField end_experience;
    private javax.swing.JMenu experienceManage;
    private javax.swing.JMenu guideManage;
    private javax.swing.JTextField image_exp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel jNom;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenu newsletterManage;
    private javax.swing.JTextField note_experience;
    private javax.swing.JLabel pays;
    private javax.swing.JButton returnExperience;
    private javax.swing.JMenu rssManage;
    private javax.swing.JTextField season_experience;
    private javax.swing.JTextField start_experience;
    private javax.swing.JMenu statManage;
    private javax.swing.JTextField statusExperience;
    private javax.swing.JLabel sur_dix;
    private javax.swing.JTextArea texte_exp;
    private javax.swing.JTextField title_experience;
    private javax.swing.JMenu userManage;
    private javax.swing.JTextField video_experience;
    // End of variables declaration//GEN-END:variables
}
