/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.esprit.entites.Compte;
import daoLayer.CompteDao;
import java.util.List;
import tables.UtilisateurAdapter;

/**
 *
 * @author mac
 */
public class GestionUtilisateur extends javax.swing.JFrame {

    /**
     * Creates new form TableauDeBord
     */
    public GestionUtilisateur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEnableUser = new javax.swing.JButton();
        btnDisableUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTableModel = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        userManage = new javax.swing.JMenu();
        guideManage = new javax.swing.JMenu();
        experienceManage = new javax.swing.JMenu();
        statManage = new javax.swing.JMenu();
        rssManage = new javax.swing.JMenu();
        newsletterManage = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEnableUser.setText("Activé");
        btnEnableUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnableUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnableUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 80, -1));

        btnDisableUser.setText("Désactivé");
        btnDisableUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisableUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnDisableUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, -1));

        userTableModel.setBackground(new java.awt.Color(153, 153, 153));
        userTableModel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        userTableModel.setForeground(new java.awt.Color(255, 255, 255));
        userTableModel.setModel(new UtilisateurAdapter());
        userTableModel.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(userTableModel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 860, 420));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/http-www.bhutantravelshop.com-wp-content-uploads-2014-07-lt.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 1150, 600));

        userManage.setText("Utilisateurs");
        userManage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userManageMouseClicked(evt);
            }
        });
        jMenuBar1.add(userManage);

        guideManage.setText("Guides");
        jMenuBar1.add(guideManage);

        experienceManage.setText("Experiences");
        jMenuBar1.add(experienceManage);

        statManage.setText("Statistiques");
        jMenuBar1.add(statManage);

        rssManage.setText("Flux Rss");
        jMenuBar1.add(rssManage);

        newsletterManage.setText("Newsletter");
        jMenuBar1.add(newsletterManage);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userManageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userManageMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_userManageMouseClicked

    private void btnEnableUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnableUserActionPerformed
        // TODO add your handling code here:

        if(userTableModel.getSelectedRow() != -1){
            CompteDao cDao = CompteDao.getInstance();
            UtilisateurAdapter userAdapter = new UtilisateurAdapter();
            List<Compte> listUser = userAdapter.getComptes();
            Compte tmpCompte = listUser.get(userTableModel.getSelectedRow());
            cDao.disableUser(tmpCompte.getId_compte(), true);
            userTableModel.setModel(new UtilisateurAdapter());

        }
    }//GEN-LAST:event_btnEnableUserActionPerformed

    private void btnDisableUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisableUserActionPerformed
        // TODO add your handling code here:
        if(userTableModel.getSelectedRow() != -1){
            CompteDao cDao = CompteDao.getInstance();
            UtilisateurAdapter userAdapter = new UtilisateurAdapter();
            List<Compte> listUser = userAdapter.getComptes();
            Compte tmpCompte = listUser.get(userTableModel.getSelectedRow());
            cDao.disableUser(tmpCompte.getId_compte(), false);
            userTableModel.setModel(new UtilisateurAdapter());

        }
    }//GEN-LAST:event_btnDisableUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionUtilisateur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDisableUser;
    private javax.swing.JButton btnEnableUser;
    private javax.swing.JMenu experienceManage;
    private javax.swing.JMenu guideManage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu newsletterManage;
    private javax.swing.JMenu rssManage;
    private javax.swing.JMenu statManage;
    private javax.swing.JMenu userManage;
    private javax.swing.JTable userTableModel;
    // End of variables declaration//GEN-END:variables
}
