/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.esprit.entites.Commentaire;
import daoLayer.CommentaireDao;
import daoLayer.ExperienceDao;
import java.util.List;
import javax.swing.JOptionPane;
import tables.CommentaireAdapter;
import tables.GuideAdapter;

/**
 *
 * @author mac
 */
public class userConsulterExperience extends javax.swing.JFrame {
    
    /**
     * Creates new form TableauDeBord
     */
    public userConsulterExperience() {
        initComponents();
        ExperienceDao experienceDao               = ExperienceDao.getInstance();

        //Get description text
           String description_experience  = experienceDao.getTextById(UserListeExperience.experiencStatic.getId_text());
        //Get country by id
           String countryExperience       = experienceDao.getCountryById(UserListeExperience.experiencStatic.getId_country());
        //Get Video by id
           String videoExperience         = experienceDao.getVideoById(UserListeExperience.experiencStatic.getId_video());
        //Get Image by id
           String imgExperience           = experienceDao.getImageById(UserListeExperience.experiencStatic.getId_video());
        //Get Compte by id
           String compteExperience        = experienceDao.getCompteById(UserListeExperience.experiencStatic.getId_compte());
           
            String season ;
            switch(UserListeExperience.experiencStatic.getSeason_experience()){
               case "1":
                   season = "Hiver";
                   break;
                   
               case "2":
                   season = "Printemps";
                   break;
                   
               case "3":
                   season = "Automne";
                   break;
                   
               case "4":
                   season = "Ete";
                   break;
                
                default:
                    season = "";
                    break;
           }
        //Get content experience
            String content;
            if(description_experience != ""){
                content = description_experience;
            }else if(videoExperience != ""){
                content = videoExperience;
            }else if(imgExperience != ""){
                content = imgExperience;
            }else{
                content = "N/A";
            }
        
           titleExperience.setText      (UserListeExperience.experiencStatic.getTitle_experience());
           autherExperience.setText     (compteExperience);
           decalageExperience.setText   (UserListeExperience.experiencStatic.getDecalage_horaire_experience()+" H");
           depenseExperience.setText    (UserListeExperience.experiencStatic.getDepense_experience()+" DT");
           startExperience.setText      (UserListeExperience.experiencStatic.getStart_experience());
           endExperience.setText        (UserListeExperience.experiencStatic.getEnd_experience());
           seasonExperience.setText     (season);
           paysExperience.setText       (countryExperience);
           contentExperience.setText    (content);
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        returnExperience = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        titleExperience = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        autherExperience = new javax.swing.JLabel();
        autreInformationPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        decalageExperience = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        depenseExperience = new javax.swing.JLabel();
        LabStartExperience = new javax.swing.JLabel();
        startExperience = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        endExperience = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        seasonExperience = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        paysExperience = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        contentExperience = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contentCommentaire = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        ratingCommentaire = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        addExperience = new javax.swing.JButton();
        enableExperience = new javax.swing.JButton();
        disableExperience = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        commentaireTableModel = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        returnExperience.setText("<< précédent");
        returnExperience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnExperienceActionPerformed(evt);
            }
        });
        getContentPane().add(returnExperience, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setText("Auteur :");

        autreInformationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Autres Information :"));

        jLabel3.setText("Décalage Horaire : ");

        jLabel4.setText("Dépense :");

        LabStartExperience.setText("Date début :");

        jLabel5.setText("Date de fin :");

        jLabel6.setText("Saison :");

        jLabel7.setText("Pays :");

        javax.swing.GroupLayout autreInformationPanelLayout = new javax.swing.GroupLayout(autreInformationPanel);
        autreInformationPanel.setLayout(autreInformationPanelLayout);
        autreInformationPanelLayout.setHorizontalGroup(
            autreInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autreInformationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(autreInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(autreInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(depenseExperience, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(decalageExperience, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(autreInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabStartExperience, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(autreInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(startExperience, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(endExperience, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(autreInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(autreInformationPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(seasonExperience, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(autreInformationPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(paysExperience, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        autreInformationPanelLayout.setVerticalGroup(
            autreInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autreInformationPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(autreInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(autreInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(decalageExperience, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(startExperience, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabStartExperience, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seasonExperience, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(autreInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(autreInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(depenseExperience, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(endExperience, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paysExperience, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(contentExperience, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentExperience, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ajouter un commentaire"));

        contentCommentaire.setColumns(20);
        contentCommentaire.setRows(5);
        jScrollPane1.setViewportView(contentCommentaire);

        jLabel9.setText("Note Expérience :");

        ratingCommentaire.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "choisir", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel10.setText("/10");

        addExperience.setText("Ajouter");
        addExperience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExperienceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addExperience, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ratingCommentaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addGap(0, 176, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ratingCommentaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addExperience, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(autreInformationPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(titleExperience, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(autherExperience, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(autherExperience, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(titleExperience, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(autreInformationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 1120, 400));

        enableExperience.setText("Activé");
        enableExperience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enableExperienceActionPerformed(evt);
            }
        });
        getContentPane().add(enableExperience, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, -1, -1));

        disableExperience.setText("Désactivé");
        disableExperience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disableExperienceActionPerformed(evt);
            }
        });
        getContentPane().add(disableExperience, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, -1, -1));

        jButton3.setText("Supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, -1, -1));

        commentaireTableModel.setModel(new CommentaireAdapter());
        jScrollPane3.setViewportView(commentaireTableModel);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 1120, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/http-www.bhutantravelshop.com-wp-content-uploads-2014-07-lt.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnExperienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnExperienceActionPerformed
        // TODO add your handling code here:
            this.returnExperienceForm();
    }//GEN-LAST:event_returnExperienceActionPerformed

    private void addExperienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExperienceActionPerformed
        // TODO add your handling code here:
            JOptionPane jop = new JOptionPane();

            if(ratingCommentaire.getSelectedItem() == "choisir")
                jop.showMessageDialog(null, "Veuillez choisir une rating", "Eroor", JOptionPane.PLAIN_MESSAGE);        

            if(contentCommentaire.getText().equalsIgnoreCase(""))
                jop.showMessageDialog(null, "Veuillez saisir votre commentaire", "Eroor", JOptionPane.PLAIN_MESSAGE);        
            
            Commentaire comm = new Commentaire();

            comm.setContentCommentaire(contentCommentaire.getText());
            comm.setRatingCommentaire(ratingCommentaire.getSelectedIndex());
            comm.setIdExperience(UserListeExperience.experiencStatic.getId_experience());
            
            CommentaireDao commDao = CommentaireDao.getInstance();
            commDao.insertEntity(comm);
    }//GEN-LAST:event_addExperienceActionPerformed

    private void enableExperienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enableExperienceActionPerformed
        // TODO add your handling code here:
            if(commentaireTableModel.getSelectedRow() != -1){
                CommentaireDao cDao = CommentaireDao.getInstance();
                CommentaireAdapter commentaireAdapter = new CommentaireAdapter();
                List<Commentaire> listCommentaire = commentaireAdapter.getCommentaires();
                Commentaire tmpCommentaire = listCommentaire.get(commentaireTableModel.getSelectedRow());
                System.out.println(tmpCommentaire.getIdCommentaire());
                cDao.disableCommentaire(tmpCommentaire.getIdCommentaire(), true);
                commentaireTableModel.setModel(new CommentaireAdapter());
            }
    }//GEN-LAST:event_enableExperienceActionPerformed

    private void disableExperienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disableExperienceActionPerformed
        // TODO add your handling code here:
        if(commentaireTableModel.getSelectedRow() != -1){
                CommentaireDao cDao = CommentaireDao.getInstance();
                CommentaireAdapter commentaireAdapter = new CommentaireAdapter();
                List<Commentaire> listCommentaire = commentaireAdapter.getCommentaires();
                Commentaire tmpCommentaire = listCommentaire.get(commentaireTableModel.getSelectedRow());
                cDao.disableCommentaire(tmpCommentaire.getIdCommentaire(), false);
                commentaireTableModel.setModel(new CommentaireAdapter());
            }
    }//GEN-LAST:event_disableExperienceActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(commentaireTableModel.getSelectedRow() != -1){
               CommentaireDao commentaireDao          = CommentaireDao.getInstance();
               CommentaireAdapter commentaireAdapter  = new CommentaireAdapter();
               List<Commentaire> listCommentaire       = commentaireAdapter.getCommentaires();
               Commentaire tmpCommentaire              = listCommentaire.get(commentaireTableModel.getSelectedRow());
               //commentaireDao.deleteEntity(tmpCommentaire);
                
               JOptionPane jop = new JOptionPane();

                if(commentaireDao.deleteEntity(tmpCommentaire)){
                    jop.showMessageDialog(null, "Suppression de commentaire avec sucess", "Sucess", JOptionPane.INFORMATION_MESSAGE);
                }
               commentaireTableModel.setModel(new CommentaireAdapter());
            }
    }//GEN-LAST:event_jButton3ActionPerformed
    
    public void returnExperienceForm(){
        UserListeExperience expForm = new UserListeExperience();
        expForm.setVisible(true);
        this.setVisible(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userConsulterExperience.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userConsulterExperience.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userConsulterExperience.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userConsulterExperience.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userConsulterExperience().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabStartExperience;
    private javax.swing.JButton addExperience;
    private javax.swing.JLabel autherExperience;
    private javax.swing.JPanel autreInformationPanel;
    private javax.swing.JTable commentaireTableModel;
    private javax.swing.JTextArea contentCommentaire;
    private javax.swing.JLabel contentExperience;
    private javax.swing.JLabel decalageExperience;
    private javax.swing.JLabel depenseExperience;
    private javax.swing.JButton disableExperience;
    private javax.swing.JButton enableExperience;
    private javax.swing.JLabel endExperience;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel paysExperience;
    private javax.swing.JComboBox ratingCommentaire;
    private javax.swing.JButton returnExperience;
    private javax.swing.JLabel seasonExperience;
    private javax.swing.JLabel startExperience;
    private javax.swing.JLabel titleExperience;
    // End of variables declaration//GEN-END:variables
}
